16808 MainProcess 2023-08-13 21:17:08,253
Traceback (most recent call last):
  File "C:\Users\Saner\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Saner\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "C:\Users\Saner\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 229, in cmd_gen
    builder.process(options)
  File "C:\Users\Saner\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\generate.py", line 156, in process
    self._obfuscate_scripts()
  File "C:\Users\Saner\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\generate.py", line 126, in _obfuscate_scripts
    os.makedirs(os.path.dirname(fullpath), exist_ok=True)
  File "C:\Users\Saner\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Dosya adý, dizin adý veya birim etiketi sözdizimi hatalý: '\\\\'
